[tool.poetry]
name = "dbt-lint"
version = "0.1.0"
description = ""
authors = ["Rawlsy-py <christopher_m_mitchell@live.co.uk>"]
readme = "README.md"
packages = [{include = "dbt_lint"}]

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
